PAYMENT_PROVIDER=stripe
STRIPE_SECRET_KEY=YOUR_STRIPE_SECRET_KEY
STRIPE_CURRENCY=eur
# URL de retour Stripe (doit etre une URL http/https valide)
# URLs neutres interceptees par le popup interne (aucune ouverture du dashboard Stripe)
STRIPE_SUCCESS_URL=https://example.com/stripe-success?session_id={CHECKOUT_SESSION_ID}
STRIPE_CANCEL_URL=https://example.com/stripe-cancel

# Signature API (optionnel) : si vide => fallback sandbox local
SIGNATURE_API_URL=
SIGNATURE_API_KEY=
SIGNATURE_API_STRICT=false

MS_GRAPH_ACCESS_TOKEN=EwBoBMl6BAAUu4TQbLz/EdYigQnDPtIo76ZZUKsAAdq3hUYVIsCt+0BRsxi4ej9lSSTlt+Eh3wTIoUk70ohphH/OO1IXWkFOW+12X4uCoMYFsXupDchwJyAM9hFchVoZx1/00y0uObyr/UT3hck6w0GjuBU1JtuVPBbB58vNrpPL51KZgXD0ik7PLMh0TSgwtNcPqDCokySuMwaEO6HZI6n0bGr1UG2piYeoAoAcR2Bo6FhiPAqa4Sy4UGqyAFpTVmx8Act+fwY8vTGsQLNGKm4QmJFoDGV3jyYM+tftmtUicfe9S81+zKut6/6LzX69c/clPnpwFozuV23sfDKv4UM8egh9QS8XZ6Z6jkRJXE4p4bzcCi2tdieopxvslIoQZgAAENiwQbsI3Q6YfcREJK5dPZowA2SMDQAiTy3SkfIDhMFewWdd+F4bejV9EasOSi75gde+lHO3/phFwJfwhxIF0Izfd+DJTEAfHepCSvNOXeX2bW0/XudVjegP8PskcnpFFU+A31yIqj1s4nP4HWrMGz0DRtqQQJliUJr0oEoH1veMLyRy97nECpMImdV74BgKzaSkt73MYtUjGgvLl5Jp4b1zXUjzhS5q/rqoSKte4ytp+Wq9i8CJEoPhEiLAFG92XE87AMBX1L4bZPf0Ox+4vuykg6DrdC9q6Kr40N3IHXFDKIX2ps8GAWOiFWDNypXG2VKqUoq5bGn4fs87Vg6enX/kN7h9i29o++/7qmPLm1MyEwXA4XwJnu27j8q9Os7NhPaDJLIP71yQ46NM7Ii0fEVzrAzzdkhNVyG8RcfgqUm6IXNYFHnjyopA8uxKkN30NEtt9V5z/koXLfg8tIJQWNgNPvq95OXgDgkLzuQ1yAuckccCFsNc1JRkXzitrJeSHvmwYHroLbCzz9IayvBR2WaArSjtG83lzdU906D1+4L1VXSJ/mgtSKqedSgMtHVuDi5n056nLA7gltDk8meNEktm6UyIMZq5IQhLmx2GyPQkE9tpX/bnMDwL+W+IZpVgad2LNWJxPKmGYtcxKf8zO3YAwqQtwTFQoGc2El9MGXSFBu8agIHXi8aIXNgnJbnLg08fm1NgybsL8cxAehkXNIlO5DdiZgwK0sSb3xKlXhDThIlSl4AIW3ZgP3Atz61/+KwAsC6WWXPQyCzJXTv35J2nAS3U/AZ+gIlvkzT4pOq3AnS3ibbW6U4CObOzHFfuFP/BghfZ1rkFfLnroQhj5FmvWHHv/1nOcaepffWRlBdnc6QsU8xhFG8lHPJkOhA3QJ91xpAcdHpCJ58o9shLZfNGOTTIz1ZDKhVXsjqlSgwbjzhVLX1ilLx0VHx96dC+2QUPKgJMh7bO1+oHBnYS6oaxfSiTtUdM3IlTA86vrlaUX2iZd/zdEQJBgXBcyQT3pLeXJMyZsPDPdlUAkLXv1eI6m+RAElO+jXkfh+iQRX6ZyY+zlIdx7EqxNcoXIM0SxwgueH/vhj4/97CIItwI/Dgg/H4D
MS_GRAPH_CALENDAR_ID=AQMkADAwATNiZmYAZC02ODQyLTJkY2MALTAwAi0wMAoARgAAA-bQ3l0u8XNIrQlQ5oY1b-YHAMANIrodn9FLgmDndO8Smd8AAAIBBgAAAMANIrodn9FLgmDndO8Smd8AAAAsI1bnAAAA
MS_GRAPH_USER_ID=

# IPInfo (localisation approximative par IP)
IPINFO_TOKEN=73a72e702c0b5e
